services:
  backend:
    build: ./backend
    container_name: docker-project-backend
    image: docker-project-backend:latest
    ports:
      - "8081:8081"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8081/health" ]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - backend_data:/app/data

  frontend:
    build: ./frontend
    container_name: docker-project-frontend
    image: docker-project-frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8080" ]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - frontend_static:/app/static

volumes:
  backend_data:
    driver: local
  frontend_static:
    driver: local

networks:
  app-network:
    driver: bridge
